name: space_walker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  animated_text_kit: ^4.2.2
  video_player: ^2.8.2
  audioplayers: ^6.4.0
  flutter_glow: ^0.3.0
  marquee: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/json/spacewalker.json
    - assets/background/
    - assets/audio/
    - assets/images/
    - assets/audio/sfx/
    - assets/audio/music/

  fonts:
    - family: SpaceMono
      fonts:
        - asset: fonts/SpaceMono-Regular.ttf
        - asset: fonts/SpaceMono-Italic.ttf
          style: italic
        - asset: fonts/SpaceMono-Bold.ttf
          weight: 700
    - family: BrunoAceSC
      fonts:
        - asset: fonts/BrunoAceSC-Regular.ttf
    - family: Electrolize
      fonts:
        - asset: fonts/Electrolize-Regular.ttf
    - family: Rajdhani
      fonts:
        - asset: fonts/Rajdhani-Light.ttf
          weight: 300
        - asset: fonts/Rajdhani-Regular.ttf
        - asset: fonts/Rajdhani-Medium.ttf
          weight: 500
        - asset: fonts/Rajdhani-Bold.ttf
          weight: 700
